server:
  port: 8080

spring:
  application:
    name: ethixnode-backend

  # THIS TELLS SPRING TO MERGE APPLICATION-SECRETS.YML IN THE BACKGROUND
  profiles:
    include: secrets
  
  datasource:
    url: jdbc:postgresql://localhost:5432/ethixnode_db
    username: ethix_admin
    password: hackathon_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # NOTICE CLIENT ID AND SECRET ARE GONE FROM HERE
  security:
    oauth2:
      client:
        registration:
          github:
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
  
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: your_mailtrap_username
    password: your_mailtrap_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379

ethixnode:
  ai:
    service:
      url: http://localhost:5000

# JWT Security Configuration
jwt:
  # This is a secure 256-bit hex key. (In production, put this in an environment variable!)
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 1 day in milliseconds (Access Token)
  refresh-expiration: 604800000 # 7 days in milliseconds (Refresh Token)